In [2]:
from pandas import read_clipboard
!uv add pandas
!uv add numpy

Resolved 97 packages in 11ms
Audited 93 packages in 14ms
Resolved 97 packages in 1ms
Audited 93 packages in 6ms

In [2]:
import pandas as pd
import numpy as np

## Zadanie 1

In [36]:
x = [_ for _ in range(1,101)]
""
index = [f"ean_{item:03d}" for item in range(1,101)]

In [37]:
series = pd.Series(x,index = index)

In [13]:
print(series)

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Length: 100, dtype: int64

## Zadanie 2

In [205]:
index = ["base"]
for i in range(2,11):
    index.append(f"pow_{i}")

In [211]:
numbers = np.vander(np.arange(1,11),11,increasing = True)
numbers = numbers[:,1:]

In [216]:
print(numbers)

[[          1           1           1           1           1           1
            1           1           1           1]
 [          2           4           8          16          32          64
          128         256         512        1024]
 [          3           9          27          81         243         729
         2187        6561       19683       59049]
 [          4          16          64         256        1024        4096
        16384       65536      262144     1048576]
 [          5          25         125         625        3125       15625
        78125      390625     1953125     9765625]
 [          6          36         216        1296        7776       46656
       279936     1679616    10077696    60466176]
 [          7          49         343        2401       16807      117649
       823543     5764801    40353607   282475249]
 [          8          64         512        4096       32768      262144
      2097152    16777216   134217728  1073741824]
 [          9          81         729        6561       59049      531441
      4782969    43046721   387420489  3486784401]
 [         10         100        1000       10000      100000     1000000
     10000000   100000000  1000000000 10000000000]]

In [42]:
df = pd.DataFrame(numbers, index = index)
print(len(index),len(numbers))

NameError: name 'numbers' is not defined

In [14]:
print(df)

NameError: name 'df' is not defined

## Zadanie 3

In [219]:
print(np.shares_memory(numbers,df))

False

In [221]:
df_shared = pd.DataFrame(numbers, index = index, copy = False)

In [222]:
print(np.shares_memory(numbers,df_shared))

True

## Zadanie 4

In [229]:
print(df.dtypes.head)
memory_usage = df_shared.memory_usage(deep=True).sum()

<bound method NDFrame.head of 0    int64
1    int64
2    int64
3    int64
4    int64
5    int64
6    int64
7    int64
8    int64
9    int64
dtype: object>

In [230]:
print(memory_usage)

1340

In [232]:
df_downcast = df.apply(pd.to_numeric,downcast = "integer")

In [234]:
memory_usage_downcasted  = df_downcast.memory_usage(deep=True).sum()

In [235]:
print(memory_usage_downcasted)

880

## Zadanie 5

In [4]:
iris = pd.read_csv('iris.data')

In [5]:
iris.columns = iris.columns.str.replace(" ","_")
print(iris.columns)

Index(['sepal_length_in_cm', 'sepal_width_in_cm', 'petal_length_in_cm',
       'petal_width_in_cm', 'class'],
      dtype='str')

In [6]:
iris[:10]

,sepal_length_in_cm,sepal_width_in_cm,petal_length_in_cm,petal_width_in_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
7,5.0,3.4,1.5,0.2,Iris-setosa
8,4.4,2.9,1.4,0.2,Iris-setosa
9,4.9,3.1,1.5,0.1,Iris-setosa

## Zadanie 7

In [7]:
iris.memory_usage().sum()

np.int64(6132)

In [8]:
iris.memory_usage(deep=True).sum()

np.int64(14282)

In [9]:
iris_numeric = iris.select_dtypes('float64').columns
iris_smaller = iris[iris_numeric].apply(pd.to_numeric, downcast="float")

In [10]:
print(iris_smaller.memory_usage(deep=True).sum())

2532

## Zadanie 8

In [41]:
iris_smaller.to_clipboard()

In [45]:
pd.read_clipboard()

,sepal_length_in_cm,sepal_width_in_cm,petal_length_in_cm,petal_width_in_cm
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3
149,5.9,3.0,5.1,1.8

In [3]:
df_new = pd.read_clipboard()

In [4]:
df_new.head(5)

Empty DataFrame
Columns: [df_new.to_pickle]
Index: []

In [48]:
!uv add pyarrow

Resolved 126 packages in 778ms
Prepared 1 package in 2.97s
Installed 1 package in 1.24s
 + pyarrow==23.0.1

## Zadanie 9

In [5]:
df_new.to_json('dane.json')

In [6]:
df_new.to_pickle('dane.pkl')

In [7]:
df_new.to_parquet('dane.parquet')